# Generated by Django 5.0.1 on 2025-11-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_categor_07b5d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_price_b6b1d7_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint',
            field=models.FloatField(blank=True, help_text='Huella de carbono en g CO2e por 100g de producto (dato real de Open Food Facts / Agribalyse)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='data_source',
            field=models.CharField(default='manual', help_text='Origen: openfoodfacts, manual, hybrid', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ecoscore_data',
            field=models.JSONField(blank=True, help_text='Datos completos del Eco-Score de Open Food Facts (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='environmental_impact_score',
            field=models.FloatField(blank=True, help_text='PEF score - Análisis de ciclo de vida completo (menor = mejor)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='green_score',
            field=models.IntegerField(blank=True, help_text='Green Score de 0-100 calculado por Open Food Facts (mayor = mejor)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_score',
            field=models.IntegerField(blank=True, help_text='Impacto del empaquetado calculado por Open Food Facts', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ecoscore',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
